-- 2026-06-22: program_types — seed доказательной базы для 15 колено-протоколов (Part B).
-- evidence_summary — пациентский регистр, живой профессиональный язык + лёгкая Markdown-разметка
--   (абзацы, «> » цитата-врезка с принципом, **жирным** ключевая база/цифра). Якорь на реальные источники протокола.
-- evidence_sources — инструкторский (исследования/гайдлайны из досье, разделитель «; »); прошли adversarial-ревью 15/15.
-- Зависит от 20260622_program_types_evidence.sql (колонки) и базовых knee-типов — сортируются раньше.
-- Идемпотентно: UPDATE по фиксированным значениям. Источник истины после деплоя — AdminContent.

BEGIN;

UPDATE program_types SET evidence_summary = 'Программа следует международным клиническим руководствам по реабилитации после пластики передней крестообразной связки (**Aspetar**, нидерландский протокол **KNGF**) и опирается на данные многолетних клинических исследований.
> Следующий этап открывает объективная готовность: восстановленная сила, полная амплитуда и контроль над коленом.
По данным исследований, соблюдение этих критериев перед возвратом к бегу и спорту заметно снижает **риск повторного разрыва**. В первые **1,5–3 месяца** трансплантат особенно уязвим, поэтому раннюю нагрузку дозируют осторожно.
Руководства признают и то, что операция показана не каждому: часть пациентов восстанавливает стабильность колена силовыми и нейромышечными упражнениями. Такое решение принимают с врачом по результатам обследования; силу оперированной ноги сравнивают со здоровой и по возможности измеряют ещё до операции.', evidence_sources = 'Aspetar CPG (Kotsifaki 2023, BJSM, GRADE); KNGF/Dutch (van Melick 2016, BJSM); van Melick 2025 (ESSKA, KSSTA); JOSPT criterion-based (Adams 2012; Brinlee 2022); OPTIKNEE 2022; Grindem 2016 (Delaware-Oslo, BJSM); Kyritsis 2016 (6 discharge criteria, BJSM); Kotsifaki 2025 («9 months sweet spot», BJSM); Wellsandt 2017 (LSI/EPIC, JOSPT); Thoma 2019 (coper/NMST, AJSM); KANON/Frobell 2013 (BMJ); Filbay 2017 (KANON, BJSM); Scheffler 2008 (ligamentization, KSSTA); Muller 2016 (PASS IKDC/KOOS, AJSM); Holmgren 2024 (graft, AJSM); Sanders 2016 / Lohmander 2007 (эпидемиология/ОА, AJSM); Клинические рекомендации Минздрав РФ 2024' WHERE code = 'acl';

UPDATE program_types SET evidence_summary = 'Программа опирается на международный консенсус по реабилитации мениска (**ESSKA–AOSSM–AASPT, 2024**) и исследования по срокам заживления шва.
> Первые недели задача одна: дать шву прижиться к ткани. Поэтому глубину сгибания и нагрузку на ногу ограничивают.
Заживление идёт постепенно, нередко **несколько месяцев**. Конкретные ранние ограничения по опоре и сгибанию задаёт оперировавший хирург: они зависят от типа и места разрыва. К бегу и спорту переходят, когда восстановлена сила и пройдены контрольные тесты.', evidence_sources = 'ESSKA-AOSSM-AASPT Meniscus Rehabilitation Consensus 2024 (Pujol Part I; Prill Part II); Lind RCT 2013 (AJSM, свободная vs ограниченная реабилитация); Calanna/Duthon/Menetrey 2022 (current concept review по типу разрыва); Mueller/LaPrade JOSPT 2016 (root-репарация); Cong AOSSM survey 2024 (OJSM, n=451); O''Donnell systematic review 2017 (AJSM); Dai second-look SR/MA 2021; Schweizer KSSTA 2022 (несостоятельность шва); Kopf ESSKA traumatic meniscus consensus 2019; Mass General Brigham Protocol 2021 + OSU Wexner Meniscus Repair CPG 2023' WHERE code = 'knee_meniscus_repair';

UPDATE program_types SET evidence_summary = 'Корень мениска прикреплён к кости. При его отрыве мениск перестаёт распределять нагрузку, и сустав изнашивается быстрее, поэтому режим строже, чем при обычном шве.
> Первые недели проходят без опоры на ногу и со сгибанием не глубже прямого угла, пока ткань не прирастёт к кости.
Ранняя нагрузка незаметно расшатывает шов и мешает ему срастись; конкретные ограничения задаёт оперировавший хирург. По данным мета-анализа (**Krivicich, 2022**), в долгой перспективе шов корня переносится лучше удаления мениска и реже приводит к замене сустава (**9,8% против 36%**).', evidence_sources = 'ESSKA-AOSSM-AASPT Meniscus Rehabilitation Consensus 2024 (Pujol Part I; Prill Part II, грейды C–D); Mueller/LaPrade JOSPT 2016 (Level V, фазовый протокол); Monson & LaPrade IJSPT 2025 (Level V, precautions/RTR-критерии); Allaire JBJS 2008 + Padalecki AJSM 2014 (биомеханика, эквивалент менискэктомии); Steineman Arthroscopy 2019 (необратимое расшатывание pull-out шва); Krivicich AJSM 2022 (мета-анализ: шов 9,8% vs резекция 36% конверсии в эндопротез); Kim Clin Orthop Surg 2023 + Benelli J Exp Orthop 2025 (систематические обзоры рехаба); Carroll OJSM 2025 (ТГВ 10,7% у пациентов >40 лет)' WHERE code = 'knee_meniscus_root_repair';

UPDATE program_types SET evidence_summary = 'При дегенеративном (возрастном) разрыве упражнения и сила дают результат не хуже операции. Это вывод крупных клинических испытаний (**FIDELITY**, **ESCAPE**, **METEOR**) и Кокрейновского обзора.
> После частичного удаления мениска защищать нечего: опираться на ногу и сгибать колено можно по самочувствию с первых дней.
Ранняя нагрузка быстрее снимает отёк и сохраняет мышцу. Сначала уходит отёк и возвращается полное выпрямление, затем полная амплитуда и сила, и только потом бег и спорт. Готовность оценивают по силе и прыжковым тестам относительно здоровой ноги.', evidence_sources = 'FIDELITY (Sihvonen, NEJM 2013; 5-летн. BJSM 2020; 10-летн. NEJM 2026); ESCAPE (Van de Graaf, JAMA 2018; 5-летн. JAMA Netw Open 2022); METEOR (Katz, NEJM 2013); Cochrane 2022 (O''Connor); BMJ Rapid Recommendation (Siemieniuk 2017); ESSKA Meniscus Consensus 2016; EU-US Meniscus Rehabilitation Consensus 2024 (Pujol/Prill, KSSTA 2025); Lee 2019 RTS review; MGH Partial Meniscectomy Protocol (2024)' WHERE code = 'knee_meniscectomy';

UPDATE program_types SET evidence_summary = 'При неоперационном разрыве мениска упражнения и постепенная нагрузка дают такой же результат, как операция: и в первые месяцы, и через **5–10 лет**. Это показали крупные клинические испытания (**ESCAPE**, **OMEX**, **FIDELITY**).
> Поэтому движение и сила здесь основной, полноценный путь восстановления.
Нагрузка не «доламывает» сустав: сильные мышцы бедра и ягодиц делают колено устойчивее и не ускоряют износ. Переход на следующий этап определяют по тому, как колено держит нагрузку, по силе и контрольным тестам.', evidence_sources = 'ESCAPE RCT (van de Graaf, JAMA 2018; 5-year follow-up 2022); OMEX RCT (Kise, BMJ 2016; 10-year Berg, BJSM 2025); METEOR RCT (Katz, NEJM 2013); FIDELITY sham-RCT (Sihvonen, NEJM 2013; 5-year BJSM 2020); Cochrane 2022 (O''Connor, CD014328, GRADE high); 2024 EU-US Meniscus Rehabilitation Consensus Part II (Prill 2025, Grade A); ESSKA Meniscus Consensus 2016 (Beaufils); Framingham incidental findings (Englund, NEJM 2008)' WHERE code = 'knee_meniscus_conservative';

UPDATE program_types SET evidence_summary = 'Пересадка мениска защищает сустав, и донорской ткани нужно время прижиться. Подход опирается на международный консенсус по трансплантации мениска (**ESSKA–AOSSM–AASPT, 2024**) и опыт крупных центров.
> Первые недели колено берегут: меньше веса на ногу, ортез, сгибание не глубже прямого угла.
Ранняя нагрузка чаще всего вредит приживающейся ткани, поэтому темп здесь намеренно медленный. К бегу и спорту допускают после тестов на силу и устойчивость и только с согласия хирурга. Бережный режим в начале напрямую влияет на то, сколько прослужит результат.', evidence_sources = 'ESSKA-AOSSM-AASPT Consensus on Meniscus Reconstruction 2024 (Pujol/Prill et al., Grade C-D); IMREF Consensus 2015; Novaretti et al. систематический обзор Arthroscopy 2019 (658 пац./688 MAT, 10-15 лет выживаемости); De Bruycker, Verdonk & Verdonk метаанализ SICOT-J 2017 (65 статей, 3157 MAT); Grassi et al. возврат к спорту Sports Health 2019; McCormick/Cole et al. AJSM 2014 (reoperation rate); Ahmed et al. обзор Arthroscopy 2022; named-протоколы Brian Cole MD / Stone Clinic / Fowler Kennedy (Getgood); MeTeOR2 RCT (Metcalfe et al., BMJ Open 2024, в процессе). Уровень доказательности — слабый (LoE III-IV, нет завершённых RCT).' WHERE code = 'knee_meniscus_allograft';

UPDATE program_types SET evidence_summary = 'При артрозе колена движение не опасно, а наоборот, помогает суставу. На этом сходятся ведущие международные руководства (**OARSI**, **NICE**) и доказательная программа **GLA:D**.
> Самую надёжную пользу дают три вещи: упражнения, понимание своего состояния и снижение веса при его избытке.
Нередко это работает не хуже и безопаснее лекарств и операции. Лёгкая боль во время занятий допустима и не означает, что сустав «стирается»: ориентируются на самочувствие, а не на снимок. Эффект держится, пока есть нагрузка, поэтому программа рассчитана надолго: сперва с поддержкой специалиста, затем самостоятельно.', evidence_sources = 'OARSI 2019 (Bannuru); ACR/AF 2019 (Kolasinski); NICE NG226 2022; Cochrane 2024 (Lawford, CD004376.pub4); Cochrane 2015 (Fransen); Goh 2019 NMA (Sports Med); IDEA RCT 2013 (Messier, JAMA); GLA:D 2017 (Skou & Roos); РФ КР «Гонартроз» 2024 (ID 868_1)' WHERE code = 'knee_oa';

UPDATE program_types SET evidence_summary = 'Программа следует международным клиническим руководствам по восстановлению после эндопротезирования колена (**APTA**, протокол ускоренного восстановления **ERAS**).
> В первые недели важнее всего вернуть полное разгибание и сгибание колена: упущенную рано амплитуду потом возвращать тяжело.
Ходить с опорой на ногу обычно разрешают уже в день операции. Четырёхглавая мышца бедра первые недели включается слабо. Это типичная реакция на операцию, она восстанавливается упражнениями, при необходимости с электростимуляцией.
Этапы привязаны к объективным ориентирам: угол сгибания, сила, ровная походка. Нагрузку наращивают ступенчато: бытовая и низкоударная активность раньше, ударная и тяжёлая позже, по согласованию с хирургом.', evidence_sources = 'APTA CPG (Jette/Phys Ther 2020); ERAS Society Consensus (Wainwright 2020); Cochrane CPM (Harvey 2014); Mizner 2005 (дефицит квадрицепса); Stevens-Lapsley NMES RCT 2012; Issa (тайминг MUA <12 нед); Bade HI vs LI RCT 2017; CORKA RCT (Barker 2020) + Fleischman/Insall RCT 2019 (HEP non-inferior); Pongcharoen UKA vs TKA RCT 2023; AHRQ SR реабилитации TKA; КР «Гонартроз» Минздрав РФ (supplementary)' WHERE code = 'knee_tka';

UPDATE program_types SET evidence_summary = 'Подход опирается на международные согласования специалистов (**Int J Surg, 2025**; Немецкое общество коленного сустава) и многолетние наблюдения за пациентами.
> Задняя крестообразная связка часто заживает сама, поэтому при лёгких и средних повреждениях упор делают на четырёхглавую мышцу бедра и защиту колена от смещения голени назад.
Такой подход даёт результат не хуже операции. Восстановление идёт медленнее, чем при передней связке: тканям, а после операции и новой связке, нужно больше времени, поэтому ранняя работа задней поверхности бедра и глубокое сгибание временно ограничены. К бегу и спорту возвращаются по восстановленной силе, балансу и уверенности в колене.', evidence_sources = 'Int J Surg expert consensus 2025 (Delphi, 90 экспертов, 17 стран); German Knee Society / DKG Delphi 2025; Bedi/Musahl/Cowan JAAOS 2016 (evidence-based review); Schroven 2022 (систобзор операция vs консервативно); Shelbourne 2013 (10+ лет, консервативное ведение) и Shelbourne 1999 (естественное течение); Jacobi 2010 (динамический PCL-брейс); Senese 2018 (обзор протоколов реабилитации); Tortoli 2026 (scoping review RTS-критериев); Kopkow JOSPT 2013 (диагностические тесты)' WHERE code = 'knee_pcl';

UPDATE program_types SET evidence_summary = 'Программа следует международному консенсусу по возвращению к спорту после операций на хряще (**2024**) и серии клинических исследований по режиму нагрузки.
> Хрящ восстанавливается месяцами, поэтому первые недели колено берегут, а нагрузку добавляют постепенно.
Какой именно режим опоры и сгибания нужен вначале, зависит от вида операции и зоны сустава; его задаёт хирург. Исследования показывают **разумную середину**: гнать к полной нагрузке рано не нужно, но и чрезмерная осторожность преимущества не даёт. К спорту возвращаются по проверкам силы, амплитуды и устойчивости.', evidence_sources = 'International Delphi Consensus on RTP after cartilage injury (Mills/Hurley/Danilkowicz et al., 2024); Ebert et al. accelerated vs traditional WB after MACI — серия РКИ (2008, 2012, 2020 10-летние исходы; 2021/2025); Wondrasch et al. RCT (2015); SUMMIT Extension RCT — MACI vs microfracture 5 лет (Brittberg, 2018); Krych et al. meta-analysis RTS (2017); Campbell et al. systematic review (2016); Mithoefer et al. JOSPT Current Concepts (2012); Edwards/Ackland/Ebert MACI Rehab Guidelines JOSPT (2014); Crowley et al. OAT/OCA rehab variability review (2022); MACI Rehabilitation Manual (Vericel / Flanigan consensus 2021)' WHERE code = 'knee_cartilage_repair';

UPDATE program_types SET evidence_summary = 'Единого международного руководства по реабилитации после шва разгибательного аппарата нет, поэтому программа собрана из исследований и протоколов крупных клиник (**West, 2008**; мета-анализ **Serino, 2017**; протокол Mass General Brigham).
> Место операции первые недели слабое и набирает прочность постепенно, поэтому колено держат выпрямленным в ортезе, а сгибание вводят осторожно.
Темп индивидуален: при дополнительном укреплении шва хирург может разрешить движение раньше, при сопутствующих болезнях медленнее. К спорту возвращаются по тестам силы и контроля ноги, обычно через несколько месяцев; точные сроки определяют хирург и физиотерапевт.', evidence_sources = 'West (AJSM) 2008; Langenhan (KSSTA) 2012; Gilmore (The Knee) 2015; Serino network meta-analysis (Injury) 2017; Haskel (KSSTA) 2021 RTS systematic review; Matthies (OJSM) 2022 survey; Brinkman (JAAOS Glob Res Rev) 2024; Mass General Brigham Patella/Quad Tendon protocol; OrthoUtah protocol; StatPearls NBK513275/NBK482389; Hjorthaug (J Orthop Res) 2015 tendon-to-bone healing; Imbergamo (OJSM) 2022 / Ettinger (AJSM) 2013 fixation biomechanics. Примечание: формального международного CPG по реабилитации после EMR нет; конфликт «ранняя мобилизация vs иммобилизация ≥6 нед» не разрешён (приведён раздельно).' WHERE code = 'knee_extensor_mechanism_repair';

UPDATE program_types SET evidence_summary = 'Программа опирается на международный консенсус по остеотомии коленного сустава (**ESSKA, 2024**) и рандомизированные исследования по срокам нагрузки.
> Остеотомия меняет положение кости, чтобы разгрузить больную часть колена, поэтому первые недели важнее всего добиться сращения кости в новом положении.
Опору на ногу добавляют постепенно, а ходьбу без костылей открывают по подтверждённому сращению. Четырёхглавая мышца бедра восстанавливается долго, нередко дольше полугода, и это нормально, поэтому в программе много силовой работы. Возврат к спорту обычно занимает от полугода до года и происходит, когда сила и тесты подтвердили готовность.', evidence_sources = 'ESSKA Consensus on Osteotomy around the varus knee Part I & II 2024; Lansdaal RCT (immediate vs delayed WB MOWHTO) 2017; Schröter RCT (early FWB vs partial WB) 2017; Schröter (smoking & unstable hinge → delayed gap filling) 2015; Brinkman RSA (early FWB safe OW-HTO) 2010; van Haeringen owHTO vs cwHTO meta-analysis 2023; Niinimäki Finnish registry 3195 HTO 2012; Loke (conversion to TKA after HTO) 2025; Miltenberg (complications after HTO) 2024; Apseloff (WB timing after DFO) 2025; Ekhtiari (return to sport after HTO) 2016; Ohio State University HTO/DFO Clinical Practice Guideline 2023' WHERE code = 'knee_osteotomy_hto_dfo';

UPDATE program_types SET evidence_summary = 'Сухожилие восстанавливается под постепенной дозированной нагрузкой; покой здесь не помогает. Это подтверждают нагрузочные программы (**Malliaras, JOSPT 2015**; **Kongsgaard, 2009**) и консенсус по терминологии (**ICON, 2019**).
> «Колено прыгуна» это перегрузка сухожилия, а не воспаление; заживает она медленно, недели и месяцы.
Умеренная боль во время занятий (примерно **до 3 из 10**), которая утихает за сутки, допустима и не вредит; если боль нарастает, нагрузку снижают. Покой и уколы, особенно гормональные, не помогают и могут навредить, а снимок готовности не показывает.', evidence_sources = 'Cook & Purdam континуум 2009 (пересмотр 2016); Malliaras 4-стадийная нагрузочная прогрессия JOSPT 2015; Kongsgaard HSR vs эксцентрика RCT 2009; Breda JUMPER RCT (PTLE) 2021; Bahr хирургия vs эксцентрика RCT 2006; Rio изометрическая аналгезия BJSM 2015 (оспорено: Holden 2020, van Ark 2016, Clifford SR 2020); Coombes кортикостероиды Lancet 2010 + JOSPT позиция 2024; ICON 2019 терминология (Scott BJSM 2020); VISA-P (Visentini 1998, MCID 13 Hernandez-Sanchez 2014, нормы Zwerver 2009)' WHERE code = 'knee_patellar_tendinopathy';

UPDATE program_types SET evidence_summary = 'При боли в передней части колена основа восстановления это движение и постепенное укрепление, а операция нужна очень редко. Это закреплено в клиническом руководстве (**JOSPT, 2019**) и международных консенсусах.
> Упражнения работают не только с коленом, но и с бедром: именно бедро управляет положением колена, и контроль над ним снижает нагрузку на сустав и боль.
Лёгкая боль во время занятий допустима, если к следующему дню возвращается к обычной. Быстрых решений здесь нет: устойчивый результат даёт последовательная работа в течение недель и месяцев, а к бегу и большим нагрузкам переходят по тому, как тело справляется с упражнениями.', evidence_sources = 'JOSPT PFP CPG 2019 (Willy, grade A); Collins 2018 Consensus (BJSM); Crossley 2016 Consensus Part 1+2 (BJSM); Nascimento 2018 (JOSPT, SR/MA, level 1a-, hip+knee > knee-alone, без прироста силы); Cochrane van der Heijden 2015 (CD010387, OKC vs CKC); Lankhorst 2016 (BJSM, прогноз 57% неблагоприятное восстановление 5-8 лет); Winters 2021 (BJSM, living network MA, education+упражнения); Esculier 2018 RCT + Bramah 2019 (gait retraining у бегунов); Silbernagel 2007 (acceptable pain / 24h-reactivity, экстраполяция); KOOS-PF (Crossley 2018) + AKPS/Kujala как PROM' WHERE code = 'knee_pfps';

UPDATE program_types SET evidence_summary = 'Современное понимание боли по наружной стороне колена изменилось: это не трение, а сдавливание чувствительной ткани под подвздошно-большеберцовым трактом (**Fairclough, 2006**).
> Боль усиливают определённое сгибание колена, бег под гору и резкий рост нагрузки.
Поэтому восстановление начинают со снижения нагрузки, чтобы убрать раздражение, затем наращивают силу и контроль движения и только потом возвращают бег или велосипед. Ориентируются на переносимость: не усиливается ли боль на следующий день; сначала ровная поверхность, спуски в последнюю очередь. Массажный ролик даёт короткое облегчение, но «удлинить» или растянуть тракт не может (**Pepper, RCT 2021**).', evidence_sources = 'Fairclough 2006 (анатомия/МРТ, реконцептуализация компрессии); Fairclough 2007; Orchard 1996 (зона импинджмента ~30°); van der Worp 2012 (систематический обзор); Ellis/Hing/Reid 2007 (систематический обзор, эпидемиология); Foch 2023 (мета-анализ, hip-strength); Fredericson 2000; Noehren 2007 (проспективный, кинематика); Grau 2008; McKay 2020 (пилотный RCT); Sanchez-Alvarado/Frontiers 2024 (систематический обзор); Meardon 2012 (ширина шага/ITB-strain); Willy/Davis 2011; Pepper 2021 (RCT 1b, миф роллинга); Chaudhry 2008; Gunter 2004 (RCT, кортикостероид); Beals/Flanigan 2013 (траектория восстановления); Fredericson/Weir 2006 (фазовый протокол return-to-run)' WHERE code = 'knee_itbs';

COMMIT;
