// =====================================================
// Shared mock data for frontend tests (Sprint 1.2)
// =====================================================

export const mockDashboardData = {
  program: {
    id: 1,
    title: 'ACL Rehab',
    diagnosis: 'Разрыв ПКС',
    current_phase: 1,
    phase_started_at: '2026-01-15',
    surgery_date: '2026-01-01',
    status: 'active',
    patient_name: 'Тест Пациент',
  },
  phase: {
    id: 1,
    phase_number: 1,
    name: 'Защита и заживление',
    icon: 'shield',
    color: '#1A8A6A',
    color2: '#2B7CB8',
    description: 'Фокус на защите трансплантата',
    duration_weeks: 6,
    videos: [
      { id: 1, title: 'Разминка', url: 'https://example.com/video', thumbnail: null, duration: '3:00' },
    ],
  },
  streak: {
    current: 5,
    best: 10,
    atRisk: false,
  },
  lastDiary: {
    id: 1,
    pain_level: 3,
    entry_date: '2026-02-10',
  },
  tip: {
    id: 1,
    title: 'Совет дня',
    body: 'Продолжайте тренировки каждый день!',
    icon: '💪',
  },
  diaryFilledToday: false,
  exercisesDoneToday: false,
};

export const mockDashboardDataNoProgram = {
  program: null,
  phase: null,
  streak: { current: 0, best: 0, atRisk: false },
  lastDiary: null,
  tip: {
    id: 1,
    title: 'Начните сегодня',
    body: 'Свяжитесь с инструктором',
  },
  diaryFilledToday: false,
  exercisesDoneToday: false,
};

// 6 фаз ACL для тестов RoadmapScreen (v12 plan: «renders all 6 phases»).
export const mockPhases = [
  {
    id: 1,
    phase_number: 1,
    name: 'Защита и заживление',
    icon: 'shield',
    color: '#818CF8',
    color_bg: '#EEF2FF',
    teaser: 'Защита трансплантата',
    duration_weeks: 12,
    week_start: 1,
    week_end: 12,
    description: 'Восстановление после операции, защита трансплантата, контроль отёка',
    goals: ['Контроль отёка', 'Защита трансплантата'],
    restrictions: ['Бег', 'Прыжки'],
    allowed: ['Ходьба с костылями'],
    pain: ['Лёд 3-4 раза в день'],
    daily: ['Не стоять более 15 минут'],
    red_flags: ['Температура > 38°'],
    criteria_next: ['Полное разгибание', 'Сгибание 90°'],
    faq: [{ question: 'Когда можно ходить?', answer: 'По рекомендации врача' }],
  },
  {
    id: 2,
    phase_number: 2,
    name: 'Ранняя мобилизация',
    icon: 'move',
    color: '#38BDF8',
    color_bg: '#EFF9FE',
    teaser: 'Восстановление подвижности',
    duration_weeks: 8,
    week_start: 13,
    week_end: 20,
    description: 'Восстановление ROM, активация квадрицепса',
    goals: ['Увеличение ROM'],
    restrictions: ['Бег'],
    allowed: ['Велотренажёр'],
    pain: ['Лёд после тренировок'],
    daily: ['Ходьба без костылей'],
    red_flags: ['Острая боль'],
    criteria_next: ['Полный ROM'],
    faq: [{ question: 'Можно ли бегать?', answer: 'Пока нет' }],
  },
  {
    id: 3,
    phase_number: 3,
    name: 'Укрепление',
    icon: 'dumbbell',
    color: '#4ADE80',
    color_bg: '#EDFAF5',
    teaser: 'Прогрессивная нагрузка',
    duration_weeks: 12,
    week_start: 21,
    week_end: 32,
    description: 'Прогрессивная нагрузка, силовая работа',
    goals: ['Сила квадрицепса'],
    restrictions: ['Ударные нагрузки'],
    allowed: ['Силовая работа'],
    pain: ['Контроль боли'],
    daily: ['Ходьба 5 км'],
    red_flags: ['Отёк после нагрузки'],
    criteria_next: ['Симметрия силы 80%'],
    faq: [],
  },
  {
    id: 4,
    phase_number: 4,
    name: 'Функциональная',
    icon: 'activity',
    color: '#FBBF24',
    color_bg: '#FEF8E8',
    teaser: 'Возврат к бегу',
    duration_weeks: 12,
    week_start: 33,
    week_end: 44,
    description: 'Возврат к бегу, проприоцепция, плиометрика',
    goals: ['Бег', 'Прыжки'],
    restrictions: ['Контактный спорт'],
    allowed: ['Бег прямо'],
    pain: ['Не более 3/10'],
    daily: ['Ступеньки без перил'],
    red_flags: ['Нестабильность'],
    criteria_next: ['Single hop ≥ 85% симметрии'],
    faq: [],
  },
  {
    id: 5,
    phase_number: 5,
    name: 'Продвинутая',
    icon: 'trophy',
    color: '#FB923C',
    color_bg: '#FEEDDC',
    teaser: 'Спорт-специфические паттерны',
    duration_weeks: 16,
    week_start: 45,
    week_end: 60,
    description: 'Спорт-специфические паттерны',
    goals: ['Вернуться к спорту'],
    restrictions: ['Соревнования'],
    allowed: ['Тренировки команды'],
    pain: ['Контроль 2/10'],
    daily: ['Полная нагрузка'],
    red_flags: ['Эпизоды подворачивания'],
    criteria_next: ['Y-balance в норме'],
    faq: [],
  },
  {
    id: 6,
    phase_number: 6,
    name: 'Поддержание',
    icon: 'star',
    color: '#A78BFA',
    color_bg: '#F4F0FD',
    teaser: 'Возврат в спорт',
    duration_weeks: null,
    week_start: 60,
    week_end: null,
    description: 'Возврат в спорт, профилактика',
    goals: ['Возврат к соревнованиям'],
    restrictions: [],
    allowed: ['Все виды нагрузок'],
    pain: ['Боли быть не должно'],
    daily: ['Нормальная жизнь'],
    red_flags: ['Новые травмы'],
    criteria_next: ['Решение спортивного врача'],
    faq: [],
  },
];

export const mockDiaryEntries = [
  {
    id: 1,
    entry_date: '2026-02-10',
    pain_level: 3,
    swelling: 0,
    exercises_done: true,
  },
  {
    id: 2,
    entry_date: '2026-02-09',
    pain_level: 5,
    swelling: 1,
    exercises_done: true,
  },
];

export const mockExerciseData = {
  program_id: 1,
  complex_id: 10,
  access_token: 'abc-123-test-token',
  program_title: 'ACL Rehab Phase 1',
  complex_title: 'Утренний комплекс',
  exercise_count: 8,
};
